# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 503)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_1.setObjectName("plainTextEdit_1")
        self.gridLayout.addWidget(self.plainTextEdit_1, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 2, 1, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout.addWidget(self.plainTextEdit_3, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(parent=Dialog)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 7, 1, 1, 1)
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.gridLayout.addWidget(self.plainTextEdit_5, 5, 1, 1, 1)
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.gridLayout.addWidget(self.plainTextEdit_6, 4, 1, 1, 1)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout.addWidget(self.plainTextEdit_4, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.save = QtWidgets.QPushButton(parent=Dialog)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название сорта"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_3.setText(_translate("Dialog", "Молотый/в зерна"))
        self.cancel.setText(_translate("Dialog", "Отменить"))
        self.label_4.setText(_translate("Dialog", "Описание вкуса"))
        self.label_6.setText(_translate("Dialog", "Обьем упаковки"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.save.setText(_translate("Dialog", "Сохранить"))
